"""
LLM-BEL Source API for INDRA.

This module provides two integration modes:

V1 — Offline processing
    Users supply JSON files generated by an external LLM BEL extraction
    pipeline. INDRA normalizes the BEL and produces INDRA Statements.

V2 — Live processing (optional)
    If the 'textToKnowledgeGraph' package is installed, INDRA can call
    the LLM extraction pipeline directly (similar to REACH/TRIPS)
    and immediately process the returned BEL relations.

Both modes produce an LlmBelProcessor instance containing INDRA
Statements derived from BEL expressions.
"""

import json
import logging
from pathlib import Path
from typing import Dict, List, Optional, Union

from indra.sources.bel import process_bel_stmt
from .processor import LlmBelProcessor
from .normalizer import prepare_bel_for_parsing

logger = logging.getLogger(__name__)



# V1 — Offline BEL file/directory/json processing
def process_llm_results_file(path: Union[str, Path]) -> LlmBelProcessor:
    """Process a single LLM-BEL JSON results file.

    Parameters
    ----------
    path : str or Path
        Path to a JSON file containing BEL relations.

    Returns
    -------
    LlmBelProcessor
        Processor containing the converted INDRA Statements.
    """
    path = Path(path)
    logger.info("Processing LLM-BEL results file: %s", path)

    with open(path, "r") as fh:
        data = json.load(fh)

    return process_llm_results_json(data)


def process_llm_results_dir(path: Union[str, Path]) -> LlmBelProcessor:
    """Process all JSON files in a directory of LLM-BEL outputs.

    Parameters
    ----------
    path : str or Path
        Directory containing multiple JSON output files.

    Returns
    -------
    LlmBelProcessor
        Processor containing the union of all INDRA Statements.
    """
    processor = LlmBelProcessor()
    path = Path(path)

    for f in sorted(path.glob("*.json")):
        logger.info("Processing file: %s", f)
        with open(f, "r") as fh:
            data = json.load(f)
        sub = process_llm_results_json(data)
        processor.statements.extend(sub.statements)

    return processor


def process_llm_results_json(data: Dict) -> LlmBelProcessor:
    """Process BEL relations returned directly from the LLM engine.

    Parameters
    ----------
    data : dict
        Dictionary containing at least a ``"relations"`` field.

    Returns
    -------
    LlmBelProcessor
        Processor with INDRA Statements derived from BEL.
    """
    relations = data.get("relations", [])
    processor = LlmBelProcessor()

    for rel in relations:
        bel_raw = rel.get("bel")
        if not bel_raw:
            continue

        # Unpack prepare_bel_for_parsing correctly
        should_process, bel_clean = prepare_bel_for_parsing(bel_raw)

        # Skip unusable / malformed BEL before calling PyBEL
        if not should_process or not bel_clean:
            continue

        # process_bel_stmt returns a PybelProcessor, not a Statement
        try:
            pbp = process_bel_stmt(bel_clean)
        except Exception as err:
            logger.error("BEL parsing error for %s: %s", bel_clean, err)
            continue

        # No processor or no statements → skip
        if pbp is None or not hasattr(pbp, "statements") or not pbp.statements:
            continue

        # iterate through all statements extracted from BEL
        for stmt in pbp.statements:
            # Every Statement should have at least one Evidence entry
            if not stmt.evidence:
                continue

            ev = stmt.evidence[0]
            ev.source_api = "LLM-BEL"
            ev.annotations.update({
                "bel": bel_raw,
                "text": rel.get("text"),
                "confidence": rel.get("confidence"),
                "pmcid": rel.get("pmcid"),
            })

            processor.statements.append(stmt)

    return processor




# V2 — Live Integration via Python Wrapper (Optional)
def process_pmc_live(pmc_id: str, api_key: str, **kwargs) -> LlmBelProcessor:
    """Run live BEL extraction using textToKnowledgeGraph, if installed.

    Parameters
    ----------
    pmc_id : str
        PMCID such as 'PMC3898398'.
    api_key : str
        OpenAI API key required by the external textToKnowledgeGraph package.
    kwargs :
        Additional keyword arguments passed to textToKnowledgeGraph.main().

    Returns
    -------
    LlmBelProcessor
        Processor containing INDRA Statements derived from live BEL output.

    Raises
    ------
    ImportError
        If textToKnowledgeGraph is not installed.
    ValueError
        If the returned data structure is unexpected.
    """
    try:
        from textToKnowledgeGraph import main as tkg_main
    except ImportError:
        raise ImportError(
            "The 'textToKnowledgeGraph' package is not installed. "
            "Install it or use V1 offline mode."
        )

    logger.info("Running live LLM-BEL extraction for %s", pmc_id)

    results = tkg_main(
        api_key=api_key,
        pmc_ids=[pmc_id],
        upload_to_ndex=False,
        **kwargs,
    )

    if not isinstance(results, dict) or "relations" not in results:
        raise ValueError(
            f"textToKnowledgeGraph returned unexpected structure: {type(results)}"
        )

    return process_llm_results_json(results)
